#!/bin/bash
#
# Copyright (c) 2024 Lancaster University
# Author: Gerard Hand
#
#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

if [[ "$1" == "" || "$2" == "" ]];then
    echo -e "\nUsage: create <source image> <container name> [<ceph version>]"
    echo -e "\nExample:\n       create centos:stream9 cephlatest pacific"
    echo -e "       create fedora:39 cephlatest\n"
    exit 1
fi

SOURCE=$1
BUILD=$2
CEPH_VERSION=$3
SESSION_NAME="build"

# Check if the tmux session exists from a previous run
if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    # Remove the log pane
    tmux kill-pane -t "$SESSION_NAME:0.1"
else
    # Create a session
    tmux new-session -d -s "$SESSION_NAME"
fi

# Split the window vertically into two panes (Current actions and logs)
tmux split-window -dI -l 75% &

# Run the script to create
tmux send-keys -t "$SESSION_NAME:0.0" "./do_create $SESSION_NAME $SOURCE $BUILD $CEPH_VERSION" Enter

tmux a

